services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - TZ=Asia/Taipei
      - N8N_USER_MANAGEMENT_DISABLED=false     
      - N8N_DIAGNOSTICS_ENABLED=false          
      - N8N_HOST=localhost                     
      - N8N_PROTOCOL=http                      
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
    volumes:
      - ./data:/home/node/.n8n
